# Basic
name:               "garnt's lab"

author:
#  facebook:         your-id
#  youtubeUser:      your-id
#  youtubeChannel:   your-id
#  twitter:          your-id
  github:           "https://github.com/garnts"
#  stackoverflow:    your-id
#  quora:            your-id
#  linkedin:         your-id
#  pinterest:        your-id
#  googlePlus:       your-id
#  instagram:        your-id
#  reddit:           your-id
#  medium:           your-id
#  tumblr:           your-id
  email:            garnt@ass.is

copyright:
  year:             2019
  name:             garnt

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               ""

# URL
url:                "https://www.ass.is" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           America/New_York
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
#  - name:           "about"
#    url:            "/about"
  - name:           "archive"
    url:            "/archive"
#  - name:           "tags"
#    url:            "/tags"
  - name:           "github"
    url:            "https://github.com/garnts"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin
  - jekyll-autoprefixer

exclude:            [vendor]
